------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [1]:
import numpy as np

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

## Crea un vector entre 7 y 66.

In [2]:
vector_7_to_66 = np.arange(7, 67)

print(vector_7_to_66)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60 61 62 63 64 65 66]


## Invierte el vector generado anteriormente.

In [3]:
vector_66_to_7 = vector_7_to_66[::-1]

print(vector_66_to_7)

[66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43
 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19
 18 17 16 15 14 13 12 11 10  9  8  7]


## Matriz de 4x4 con valores entre 0 y 15.

In [4]:
matriz_0_to_15 = np.arange(0,16).reshape(4,4)

print(matriz_0_to_15)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Crea la matriz identidad de 5x5.

In [5]:
identidad_5 = np.identity(5)

print(identidad_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.

In [6]:
matriz_bordes = np.zeros((5, 5))

# Establecemos el valor de 1 en el centro de la matriz
matriz_bordes[2, 2] = 1

# Establecemos los valores de 1 en los bordes de la matriz
matriz_bordes[0, :] = 1
matriz_bordes[4, :] = 1
matriz_bordes[:, 0] = 1
matriz_bordes[:, 4] = 1

print(matriz_bordes)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.

In [7]:
matriz_in_crescendo = np.zeros((4, 4))

# Llenamos cada fila con valores in crescendo, de 3 a 0
for fila in range(4):
    matriz_in_crescendo[fila] = np.arange(3, -1, -1)

print(matriz_in_crescendo)

[[3. 2. 1. 0.]
 [3. 2. 1. 0.]
 [3. 2. 1. 0.]
 [3. 2. 1. 0.]]


## Crea un array de ceros de 2x7.

In [8]:
matriz_zeros = np.zeros((2, 7))

print(matriz_zeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.

In [9]:
matriz_zeros_y_unos = np.zeros((5, 4))

# Establecemos el valor de 1 en la primera fila de la matriz
matriz_zeros_y_unos[0, :] = 1

print(matriz_zeros_y_unos)

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [10]:
# Creamos un array de ceros de 8x8
tablero_ajedrez = np.zeros((8, 8), dtype=int)

# Asignamos los valores de 1 a las celdas negras
tablero_ajedrez[1::2, ::2] = 1
tablero_ajedrez[::2, 1::2] = 1

print(tablero_ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
